import mysql.connector as mysql
conn = mysql.connect(user="root", password="scott", host='127.0.0.1')
c = conn.cursor()
c.execute("USE FYCS")
c.execute("insert into student values(1, 'Ajoop')")
c.execute("insert into student values(2, 'Ahens')")
c.execute("insert into student values(3, 'anianus')")
c.execute("insert into student values(4, 'Aehtivin')")
c.execute("insert into student values(5, 'Ilatim')")
conn.commit()
c.execute("select * from student")
print(c.fetchall())
conn.close()
