file1 = open("myfile.txt", "w")
file1.write("hello world\n")
file1.writelines("This is fycs\nThis is pp practical\nROLLNO73\n")
file1.close()
file1 = open("myfile.txt", "r+")
print("Output of Read function is")
print(file1.read())
file1.seek(0)
print("Output of Readline function is")
print(file1.readline())

file1.seek(0)
print("Output of read(4)function is")
print(file1.read(4))
file1.seek(0)
print("Output of Readline(4) is")
print(file1.readline(4))
file1.seek(0)
print("output of Readlines function is")
print(file1.readlines())
file1.close()
